[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/imposterguidebook"
  to = "/imposterguidebook.html"
  status = 200

[[redirects]]
  from = "/imposterguidebook/"
  to = "/imposterguidebook.html"
  status = 200

[[redirects]]
  from = "/developing-clinician-path"
  to = "/developing-clinician-path.html"
  status = 200

[[redirects]]
  from = "/developing-clinician-path/"
  to = "/developing-clinician-path.html"
  status = 200

[[redirects]]
  from = "/established-clinician-path"
  to = "/established-clinician-path.html"
  status = 200

[[redirects]]
  from = "/established-clinician-path/"
  to = "/established-clinician-path.html"
  status = 200

[[redirects]]
  from = "/workshop-feedback"
  to = "/workshop-feedback.html"
  status = 200

[[redirects]]
  from = "/workshop-feedback/"
  to = "/workshop-feedback.html"
  status = 200

[[redirects]]
  from = "/mini-playbook"
  to = "/mini-playbook.html"
  status = 200

[[redirects]]
  from = "/mini-playbook/"
  to = "/mini-playbook.html"
  status = 200

[[redirects]]
  from = "/official-playbook"
  to = "/official-playbook.html"
  status = 200

[[redirects]]
  from = "/official-playbook/"
  to = "/official-playbook.html"
  status = 200

[[redirects]]
  from = "/brand-playbook"
  to = "/mini-playbook"
  status = 301

[[redirects]]
  from = "/brand-playbook/"
  to = "/mini-playbook"
  status = 301

[[redirects]]
  from = "/brand-playbook.html"
  to = "/mini-playbook"
  status = 301

[[redirects]]
  from = "/course"
  to = "/course/"
  status = 301

[[redirects]]
  from = "/confident-clinician-playbook"
  to = "/official-playbook"
  status = 301

[[redirects]]
  from = "/confident-clinician-playbook/"
  to = "/official-playbook"
  status = 301

[[redirects]]
  from = "/confident-clinician-playbook.html"
  to = "/official-playbook"
  status = 301
