const confidenceItems = [
  "I can notice my own activation without immediately losing focus on the client.",
  "I can tolerate a few seconds of silence without rushing to fill it.",
  "When I feel unsure, I can slow down enough to think clinically.",
  "I can stay emotionally present without absorbing responsibility for the client's entire outcome.",
  "I can recover during a session after saying something awkward, unclear, or imperfect.",
  "I can identify the main clinical thread of a session.",
  "I can collaboratively establish or clarify a useful focus.",
  "I can redirect a session without feeling controlling or rude.",
  "I can move a session toward a meaningful ending instead of abruptly stopping.",
  "I can maintain flexible structure when a client brings multiple important concerns.",
  "I can explain why I am choosing a specific question, reflection, intervention, or pause.",
  "I can decide what matters most when several possible interventions could fit.",
  "I can respond to “I don't know” without panicking or interrogating the client.",
  "I can distinguish between a moment that needs support, exploration, challenge, or consultation.",
  "I can use a framework without becoming scripted or robotic.",
  "After a difficult session, I can reflect without turning it into proof that I am failing.",
  "I can identify what belongs to me and what belongs to the client.",
  "I know when a clinical question belongs in supervision or consultation.",
  "I can make a specific plan for the next session and then stop mentally replaying the current one.",
  "I trust that confidence can include uncertainty, consultation, and continued learning.",
];

const interferenceItems = [
  "I overprepare because I am afraid I will not know what to do.",
  "I ask another question quickly because silence makes me uncomfortable.",
  "I reach for a worksheet or technique mainly because I feel stuck.",
  "I take excessive responsibility for whether the client changes.",
  "I avoid redirecting even when the session has lost direction.",
  "I soften or avoid clinically useful feedback because I am afraid the client will dislike me.",
  "I mentally replay sessions long after work ends.",
  "I compare myself to more experienced clinicians and assume they always know exactly what to say.",
  "I confuse feeling anxious with practicing badly.",
  "I leave a session without a clear idea of what I am tracking next.",
];

const ratingFields = (prefix = "") => [
  ...confidenceItems.map((label, index) => ({ key: `${prefix}confidence-${index + 1}`, label, type: "rating", min: 0, max: 10, help: "0 = not at all true · 10 = consistently true" })),
  ...interferenceItems.map((label, index) => ({ key: `${prefix}interference-${index + 1}`, label, type: "rating", min: 1, max: 5, help: "1 = never · 5 = almost every session" })),
];

const pulseCore = [
  { key: "grounded", label: "This week, I could access what I knew even when I felt activated.", type: "rating", min: 0, max: 10 },
  { key: "structure", label: "This week, I gave sessions enough structure without becoming rigid.", type: "rating", min: 0, max: 10 },
  { key: "intentional", label: "This week, I chose at least one response intentionally rather than reactively.", type: "rating", min: 0, max: 10 },
  { key: "recovery", label: "This week, I reflected on sessions without spiraling afterward.", type: "rating", min: 0, max: 10 },
  { key: "lesson-tool", label: "I completed the lesson and tool.", type: "choice", options: ["Yes", "Partly", "No"] },
  { key: "practice", label: "I practiced the weekly skill in a real or fictional case.", type: "choice", options: ["Yes", "Partly", "No"] },
  { key: "win", label: "One specific win from this week", type: "text" },
  { key: "stuck", label: "One moment I still got stuck", type: "text" },
  { key: "support", label: "What support would be most useful next week?", type: "text" },
];

const pulseSpecific = [
  "What did you notice about the moment your clinical thinking goes offline? Name the trigger, the story your brain told, and what you did next.",
  "Describe one moment when you used Center, Listen, Evaluate, Act, or Reflect. Which step helped most?",
  "Where did you create focus, redirect, tolerate silence, or close a session more intentionally?",
  "Describe one session you closed more cleanly. What did you learn, what is the next step, and what are you intentionally leaving at work?",
];

window.TCC_LAB_FORMS = {
  baseline: {
    title: "Baseline Clinical Confidence Assessment",
    eyebrow: "Before Week 1",
    description: "Answer from how you have actually practiced during the last 30 days. This is for learning and program improvement—not a test of competence.",
    fields: [
      ...ratingFields(),
      { key: "quiet-scenario", label: "The quiet session: What do you notice, what might matter clinically, and what would you do or say next—and why?", type: "text" },
      { key: "everything-scenario", label: "The everything session: What thread would you listen for, and how might you create focus without dismissing what the client brought?", type: "text" },
      { key: "carry-home-scenario", label: "The session you carry home: What belongs to reflection, what belongs in consultation, and what would help you close the loop?", type: "text" },
      { key: "confidence-drop", label: "What is the most common moment in session when your confidence drops?", type: "text" },
      { key: "usual-response", label: "What do you usually do when that happens?", type: "text" },
      { key: "desired-change", label: "What would you like to do differently by the end of four weeks?", type: "text" },
      { key: "useful-proof", label: "How would you know this program was genuinely useful—not just interesting?", type: "text" },
    ],
  },
  "success-plan": {
    title: "Personal Clinical Confidence Success Plan",
    eyebrow: "Before Week 1",
    description: "Choose a few visible behaviors—not a total personality transformation.",
    fields: [
      { key: "drop-moment", label: "My main confidence-drop moment", type: "text" },
      { key: "interrupt-pattern", label: "The pattern I want to interrupt", type: "text" },
      { key: "new-process", label: "The new process I want to practice", type: "text" },
      { key: "target-1", label: "In-session target 1: what I will do and how I will know", type: "text" },
      { key: "target-2", label: "In-session target 2: what I will do and how I will know", type: "text" },
      { key: "after-target", label: "After-session target: what I will do and how I will know", type: "text" },
      { key: "reminder", label: "When I am tempted to overcomplicate this program, I will remind myself…", type: "text" },
      { key: "formal-support", label: "The person or system I will use for required clinical supervision or consultation is…", type: "text" },
      { key: "scope-ack", label: "I agree to use de-identified or fictional material and formal support for risk, ethics, law, scope, competence, or workplace policy.", type: "acknowledgement" },
    ],
  },
  ...Object.fromEntries(pulseSpecific.map((specific, index) => [`pulse-${index + 1}`, {
    title: `Week ${index + 1} Pulse Check`,
    eyebrow: `End of Week ${index + 1}`,
    description: "A three-to-five-minute check-in to make your progress visible.",
    week: index + 1,
    fields: [...pulseCore, { key: "week-specific", label: specific, type: "text" }],
  }])),
  post: {
    title: "Post-Program Clinical Confidence Assessment",
    eyebrow: "After Week 4",
    description: "Repeat the same measures so you can compare your access to the process—not prove competence.",
    week: 4,
    fields: [
      ...ratingFields("post-"),
      { key: "different-now", label: "What is one thing you do differently in session now?", type: "text" },
      { key: "handled-uncertainty", label: "Describe one specific moment when you handled uncertainty differently.", type: "text" },
      { key: "clear-natural", label: "Which CLEAR step do you use most naturally now?", type: "text" },
      { key: "clear-practice", label: "Which CLEAR step still needs practice?", type: "text" },
      { key: "continue", label: "What will you continue practicing over the next 30 days?", type: "text" },
      { key: "useful", label: "The program gave me a process I can actually use.", type: "rating", min: 1, max: 5 },
      { key: "valuable", label: "The most valuable part was…", type: "text" },
      { key: "improve", label: "The part that needs improvement is…", type: "text" },
    ],
  },
  capstone: {
    title: "CLEAR Method Capstone",
    eyebrow: "After Week 4",
    description: "Use one fictional or fully de-identified clinical situation. This shows how you think—not whether you found one perfect intervention.",
    week: 4,
    fields: [
      { key: "situation", label: "Brief description of the situation using only the minimum de-identified context", type: "text" },
      { key: "center-notice", label: "C — What did you notice in your body, emotions, thoughts, or urges?", type: "text" },
      { key: "center-return", label: "C — How did you, or how could you, return your attention to the client and the room?", type: "text" },
      { key: "listen-thread", label: "L — What seemed most clinically important beneath the content?", type: "text" },
      { key: "evaluate-need", label: "E — What did the client need most in that moment, and what factors shaped your decision?", type: "text" },
      { key: "act", label: "A — What did you choose to do or say, and why was it more intentional than your automatic pattern?", type: "text" },
      { key: "alternative", label: "A — What was another reasonable option, and why did you not choose it then?", type: "text" },
      { key: "reflect", label: "R — What happened next, and what did you learn?", type: "text" },
      { key: "follow-up", label: "R — What would you continue, adjust, document, or bring to supervision or consultation?", type: "text" },
      { key: "release", label: "R — What can you intentionally stop carrying after this reflection?", type: "text" },
      { key: "deidentify-ack", label: "I confirm that this submission contains no identifying client information.", type: "acknowledgement" },
    ],
  },
  "call-prep": {
    title: "Private Completion Session Prep",
    eyebrow: "After Week 4",
    description: "Bring one pattern, one question, and one useful next step—not an entire caseload.",
    week: 4,
    fields: [
      { key: "skill-used", label: "What skill have you used most since the program began?", type: "text" },
      { key: "situation", label: "Describe one fully de-identified situation where you used it.", type: "text" },
      { key: "better", label: "What went better than your old pattern?", type: "text" },
      { key: "confusing", label: "What still felt confusing or uncomfortable?", type: "text" },
      { key: "support", label: "What feedback, role-play, or decision support would help?", type: "text" },
      { key: "next-behavior", label: "What repeatable behavior do you want to keep practicing?", type: "text" },
      { key: "scope-ack", label: "I confirm that any client material is fully de-identified and this session is educational mentorship—not clinical supervision or emergency consultation.", type: "acknowledgement" },
    ],
  },
};
