const intensiveCourse = {
  title: "The Confident Clinician Intensive",
  program: "Confident Clinician Intensive",
  weeks: [
    {
      number: 1,
      title: "Why Confidence Feels Shaky Early On",
      shortTitle: "You Are Not Behind",
      description: "Separate real skill gaps from confidence loops and choose one behavior-based experiment.",
      tool: "Confidence Block Inventory",
      milestone: true,
      feedbackFocus: "Confidence Block Inventory",
    },
    {
      number: 2,
      title: "The Therapist Nervous System",
      shortTitle: "Return to the Room",
      description: "Notice your therapist stress response and practice a proportionate return plan.",
      tool: "Therapist Activation Map",
    },
    {
      number: 3,
      title: "The CLEAR Method™ and Clinical Decision-Making",
      shortTitle: "Think Clearly Under Pressure",
      description: "Center, listen, evaluate, act, and reflect without turning uncertainty into panic.",
      tool: "CLEAR Decision Map",
      milestone: true,
      feedbackFocus: "CLEAR Scenario",
    },
    {
      number: 4,
      title: "Session Structure and Flow",
      shortTitle: "Structure Without Rigidity",
      description: "Open, focus, explore, intervene, redirect, and close with flexible structure.",
      tool: "Session Flow Map",
    },
    {
      number: 5,
      title: "Case Conceptualization and the Treatment Thread",
      shortTitle: "Find the Clinical Thread",
      description: "Organize the client’s patterns, protections, context, needs, and goals into a usable map.",
      tool: "5-Lens Clinical Clarity Map",
      milestone: true,
      feedbackFocus: "5-Lens Map",
    },
    {
      number: 6,
      title: "Modalities Without the Overwhelm",
      shortTitle: "Choose With Intention",
      description: "Use modalities as lenses and tools instead of a collection you must perform perfectly.",
      tool: "My Modality Map",
    },
    {
      number: 7,
      title: "Difficult Session Moments and Complex Clients",
      shortTitle: "Stay Grounded in Hard Moments",
      description: "Respond to silence, intensity, resistance, and uncertainty with observable clinical reasoning.",
      tool: "Difficult Client Reflection Map",
      milestone: true,
      feedbackFocus: "Difficult Client Map",
    },
    {
      number: 8,
      title: "Boundaries, Rupture, Repair, and Client Feedback",
      shortTitle: "Be Direct Without Becoming Rigid",
      description: "Address boundary strain, disappointment, and relational repair without over-apologizing.",
      tool: "Boundary Leak Audit + Repair Script",
    },
    {
      number: 9,
      title: "Know What Is Yours to Hold",
      shortTitle: "Clarify Responsibility",
      description: "Distinguish responsibility, influence, client agency, consultation, documentation, and escalation.",
      tool: "Responsibility + Ethics Map",
      milestone: true,
      feedbackFocus: "Responsibility + Ethics Map",
    },
    {
      number: 10,
      title: "Emotionally Demanding Work Without Letting It Consume You",
      shortTitle: "Recover With Intention",
      description: "Identify your clinical load and build realistic transitions out of the workday.",
      tool: "Clinical Load and Recovery Plan",
    },
    {
      number: 11,
      title: "Advocate for the Therapist You Are Becoming",
      shortTitle: "Name What You Need",
      description: "Practice professional self-advocacy and identify the support your next stage requires.",
      tool: "Advocacy Map",
    },
    {
      number: 12,
      title: "Become the Clinician You Can Trust",
      shortTitle: "Integrate What You Know",
      description: "Gather evidence of growth and choose grounded priorities for your next 90 days.",
      tool: "Clinical Identity Map + 90-Day Plan",
      milestone: true,
      feedbackFocus: "Post-assessment + 90-Day Plan",
    },
  ],
  activityTypes: [
    "Lesson accessed",
    "Tool completed",
    "Case exercise completed",
    "Implementation completed",
    "Reflection completed",
  ],
};

const labCourse = {
  title: "The Clinical Confidence Lab",
  program: "Clinical Confidence Lab",
  orientation: {
    number: 0,
    title: "Before You Begin",
    shortTitle: "Start Here",
    description: "",
    tool: "Video and starting check-in",
    milestone: false,
  },
  weeks: [
    {
      number: 1,
      title: "Understand Yourself",
      shortTitle: "Understand Yourself",
      description: "Understand why confidence feels shaky, identify what is actually getting in the way, and begin practicing like the clinician you want to become.",
      tool: "Emerging Clinician Identity Plan",
      milestone: true,
      feedbackFocus: "Week 1 Integration Check",
      outcome: "I can identify what is happening when my confidence drops and choose a developmental response instead of treating discomfort as proof that I do not belong.",
      agenda: [
        ["You Are Not Behind", "Understand the gap between entering the role and feeling fully identified with it."],
        ["Confidence Is Built, Not Bestowed", "Build confidence through action, reflection, and evidence."],
        ["Why Graduate School Couldn’t Finish the Job", "Identify where a clinical skill sits in the integration process."],
        ["Why ‘I Have No Idea What I’m Doing’ Is Usually the Wrong Diagnosis", "Identify the actual source of difficulty and match it with the support it needs."],
        ["Your Personal Patterns Do Not Stay Outside the Therapy Room", "Notice when personal protection becomes clinical behavior."],
        ["What Happens to Your Brain When You Feel Evaluated", "Recognize activation and practice returning attention to the client."],
        ["The Confidence Loop", "Map how uncertainty can create its own painful evidence."],
        ["Becoming the Therapist You Want to Be", "Choose observable behaviors that build a trustworthy clinical identity."],
      ],
    },
    {
      number: 2,
      title: "Getting Unstuck in the Room",
      shortTitle: "Think While Uncertain",
      description: "Slow the urgency, listen beneath the content, prioritize what matters, choose a purposeful response, and adjust using new information.",
      tool: "CLEAR Decision Map",
      milestone: true,
      feedbackFocus: "Week 2 Integration Check",
      outcome: "I can use a trustworthy reasoning process when the next step is not obvious.",
      agenda: [
        ["Why Your Brain Goes Blank", "Slow the pressure to answer before deciding what the moment needs."],
        ["Center Before You Decide", "Recover enough attention and choice to think clinically."],
        ["Listen for the Thread, Not Just the Story", "Hear emotion, meaning, pattern, protection, relationship, and need beneath the facts."],
        ["Not Everything Important Is Most Important Right Now", "Prioritize with attention to safety, capacity, readiness, and clinical purpose."],
        ["Choose the Intervention by Its Job", "Select an action for its function rather than for how impressive it sounds."],
        ["An Intervention Is a Hypothesis", "Observe impact, update your understanding, and recalibrate."],
        ["There Is Rarely One Right Answer", "Compare responsible options without hunting for certainty."],
        ["Thinking Like a Confident Clinician", "Watch the full CLEAR reasoning process applied in real time."],
      ],
    },
    {
      number: 3,
      title: "From Conversation to Clinical Movement",
      shortTitle: "Lead the Session",
      description: "Create direction without control, move from conversation into clinical work, use your natural voice, and close with intention.",
      tool: "Flexible Session Flow Map",
      milestone: true,
      feedbackFocus: "Week 3 Integration Check",
      outcome: "I can give a session purpose and movement while remaining collaborative and responsive.",
      agenda: [
        ["Structure Is Not Control", "Use structure to hold purpose, time, safety, and direction."],
        ["The First Ten Minutes Matter", "Open with connection, meaningful updates, and a shared focus."],
        ["Give the Session a Destination", "Connect the topic to a clinical target and treatment direction."],
        ["Move From Talking About Life to Doing Therapy", "Use the clinical pivot when enough understanding has been built."],
        ["Stop Performing ‘Therapist’", "Translate borrowed clinical language into a voice that sounds like you."],
        ["Redirect Without the Apology Tour", "Interrupt and refocus collaboratively when the work drifts."],
        ["Create Movement Without Forcing a Breakthrough", "Choose the kind of movement the client is ready for."],
        ["End the Session Like the Frame Matters", "Signal, select, integrate, continue, and close."],
      ],
    },
    {
      number: 4,
      title: "Become a Clinician You Can Trust",
      shortTitle: "Lead Yourself",
      description: "Reflect without punishment, hold responsibility wisely, repair when needed, use support, and build professional self trust through repeated behavior.",
      tool: "30 Day Clinician Growth Plan",
      milestone: true,
      feedbackFocus: "Week 4 Integration Check",
      outcome: "I can review my work honestly, take the next responsible step, use support appropriately, and let the session end.",
      agenda: [
        ["Reflection Is Supposed to End", "Turn useful information into a next step and an endpoint."],
        ["Responsibility Is Not Total Control", "Separate what is yours to do, influence, release, and share with support."],
        ["The Rescue Trap", "Notice when helping becomes overfunctioning."],
        ["When You Are Not Sure What to Do Next", "Use four decision questions when there is no obvious answer."],
        ["Confidence Includes Repair", "Notice impact, own your part, understand, repair, and learn."],
        ["The Seven-Minute Post-Session Debrief", "Capture what matters and create a real stopping point."],
        ["The Clinician You Can Trust", "Define trustworthiness through behavior rather than perfection."],
        ["Your Next 30 Days", "Choose a focused 30 day identity based practice plan."],
      ],
    },
    {
      number: 5,
      isBonus: true,
      title: "Bonus Clinical Lab",
      shortTitle: "Common Moments That Make Therapists Panic",
      description: "Use the course reasoning process in moments that tend to make therapists rush, rescue, reassure, defend, or freeze.",
      tool: "Common Clinical Moments Field Guide",
      milestone: false,
      outcome: "I can slow down, understand what the moment may mean, choose a proportionate response, and adjust without reaching for a canned script.",
      agenda: [
        ["When the Client Says ‘I Don’t Know’", "Treat short answers as clinical information and explore what may be limiting access."],
        ["The Client Went Silent... Now What?", "Stay with silence long enough to understand its function before filling it."],
        ["When the Emotion Gets Big", "Distinguish emotional contact from overwhelm and respond to the client’s capacity."],
        ["When the Client Wants You to Decide", "Offer useful support without taking over the client’s thinking, choice, or responsibility."],
        ["When the Client Questions You or the Therapy", "Receive difficult feedback without immediately reassuring, defending, or persuading."],
        ["When the Client Wants More of You", "Respond thoughtfully to personal questions, self disclosure, shared experience, and touch requests."],
        ["Personal Panic Pattern Inventory", "Identify which common moments activate you and the protective response you reach for."],
        ["Panic to Process Case Lab", "Practice thoughtful reasoning with four fictional clinical moments."],
        ["The Natural Language Bank", "Choose flexible language by clinical function without relying on canned answers."],
        ["The Common Clinical Moments Field Guide", "Review what to notice, what to consider, and what you might say across fourteen common moments."],
      ],
    },
  ],
  activityTypes: [
    "Lesson accessed",
    "Tool completed",
    "Implementation completed",
    "Reflection completed",
  ],
};

window.TCC_COURSES = {
  "Clinical Confidence Lab": labCourse,
  "Confident Clinician Intensive": intensiveCourse,
};
window.TCC_COURSE = labCourse;
