window.TCC_COURSE = {
  title: "The Confident Clinician Founding Cohort",
  weeks: [
    {
      number: 1,
      title: "Why Confidence Feels Shaky Early On",
      shortTitle: "You Are Not Behind",
      description: "Separate real skill gaps from confidence loops and choose one behavior-based experiment.",
      tool: "Confidence Block Inventory",
      milestone: true,
      feedbackFocus: "Confidence Block Inventory",
    },
    {
      number: 2,
      title: "The Therapist Nervous System",
      shortTitle: "Return to the Room",
      description: "Notice your therapist stress response and practice a proportionate return plan.",
      tool: "Therapist Activation Map",
    },
    {
      number: 3,
      title: "The CLEAR Method™ and Clinical Decision-Making",
      shortTitle: "Think Clearly Under Pressure",
      description: "Center, listen, evaluate, act, and reflect without turning uncertainty into panic.",
      tool: "CLEAR Decision Map",
      milestone: true,
      feedbackFocus: "CLEAR Scenario",
    },
    {
      number: 4,
      title: "Session Structure and Flow",
      shortTitle: "Structure Without Rigidity",
      description: "Open, focus, explore, intervene, redirect, and close with flexible structure.",
      tool: "Session Flow Map",
    },
    {
      number: 5,
      title: "Case Conceptualization and the Treatment Thread",
      shortTitle: "Find the Clinical Thread",
      description: "Organize the client’s patterns, protections, context, needs, and goals into a usable map.",
      tool: "5-Lens Clinical Clarity Map",
      milestone: true,
      feedbackFocus: "5-Lens Map",
    },
    {
      number: 6,
      title: "Modalities Without the Overwhelm",
      shortTitle: "Choose With Intention",
      description: "Use modalities as lenses and tools instead of a collection you must perform perfectly.",
      tool: "My Modality Map",
    },
    {
      number: 7,
      title: "Difficult Session Moments and Complex Clients",
      shortTitle: "Stay Grounded in Hard Moments",
      description: "Respond to silence, intensity, resistance, and uncertainty with observable clinical reasoning.",
      tool: "Difficult Client Reflection Map",
      milestone: true,
      feedbackFocus: "Difficult Client Map",
    },
    {
      number: 8,
      title: "Boundaries, Rupture, Repair, and Client Feedback",
      shortTitle: "Be Direct Without Becoming Rigid",
      description: "Address boundary strain, disappointment, and relational repair without over-apologizing.",
      tool: "Boundary Leak Audit + Repair Script",
    },
    {
      number: 9,
      title: "Know What Is Yours to Hold",
      shortTitle: "Clarify Responsibility",
      description: "Distinguish responsibility, influence, client agency, consultation, documentation, and escalation.",
      tool: "Responsibility + Ethics Map",
      milestone: true,
      feedbackFocus: "Responsibility + Ethics Map",
    },
    {
      number: 10,
      title: "Emotionally Demanding Work Without Letting It Consume You",
      shortTitle: "Recover With Intention",
      description: "Identify your clinical load and build realistic transitions out of the workday.",
      tool: "Clinical Load and Recovery Plan",
    },
    {
      number: 11,
      title: "Advocate for the Therapist You Are Becoming",
      shortTitle: "Name What You Need",
      description: "Practice professional self-advocacy and identify the support your next stage requires.",
      tool: "Advocacy Map",
    },
    {
      number: 12,
      title: "Become the Clinician You Can Trust",
      shortTitle: "Integrate What You Know",
      description: "Gather evidence of growth and choose grounded priorities for your next 90 days.",
      tool: "Clinical Identity Map + 90-Day Plan",
      milestone: true,
      feedbackFocus: "Post-assessment + 90-Day Plan",
    },
  ],
  activityTypes: [
    "Lesson accessed",
    "Tool completed",
    "Case exercise completed",
    "Implementation completed",
    "Reflection completed",
  ],
};
